# Generated by Django 6.1.1 on 2026-09-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
