# Generated by Django 6.1.1 on 2026-09-12 18:01

import event.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_events_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=event.models.Image_path),
        ),
    ]
