# Generated by Django 6.1.1 on 2026-09-16 14:07

import event.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to=event.models.qr_code),
        ),
    ]
