# Generated by Django 6.1.1 on 2026-09-16 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_booking_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
    ]
